name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "âœ¨ Feat"
    labels: "âœ¨ Feat"
  - title: "ğŸ”¨ Refactor"
    labels: "ğŸ”¨ Refactor"
  - title: "ğŸŒˆ Style"
    labels: "ğŸŒˆ Style"
  - title: "ğŸ§¨ Fix"
    label: "ğŸ§¨ Fix"
  - title: "â¤´ï¸Â Merge"
    labels: "â¤´ï¸Â Merge"
  - title: "ğŸ“ƒ Documentation"
    labels: "ğŸ“ƒ Documentation"
  - title: "ğŸ™‹â€â™‚ï¸ Question"
    labels: "ğŸ™‹â€â™‚ï¸ Question"

category-template: "### $TITLE"
change-template: "- $TITLE #$NUMBER @$AUTHOR "
template: |
  ## Summary

  ## Changes
  $CHANGES
